sound_tools:
  mics:
    - id: 'mic1'
      x: -0.4
      y: -0.4
      z: 0.4
      rx: 0.0
      ry: 0.0
      rz: -0.9238795
      rw: 0.3826834
    - id: 'mic2'
      x: -0.4
      y: 0.4
      z: 0.0
      rx: 0.0
      ry: 0.0
      rz: 0.9238795
      rw: 0.3826834
    - id: 'mic3'
      x: 0.4
      y: 0.4
      z: 0.4
      rx: 0.0
      ry: 0.0
      rz: 0.3826834
      rw: 0.9238795
    - id: 'mic4'
      x: 0.4
      y: -0.4
      z: 0.0
      rx: 0.0
      ry: 0.0
      rz: -0.3826834
      rw: 0.9238795
  # sound_generator:
  sound_sources:
    - file: '400Hz.wav'
      type: 'speaker'
      x: 2
      y: -2
      z: 2
    - file: '600Hz.wav'
      type: 'speaker'
      x: -2
      y: -2
      z: 2
    - file: '800Hz.wav'
      type: 'speaker'
      x: -2
      y: 2
      z: 2
    - file: '1000Hz.wav'
      type: 'speaker'
      x: 2
      y: 2
      z: 2