sound_tools:
  mics:
    - id: 'mic1'
      x: 0.0
      y: 0.4
      z: 0.0
      rx: 0.0
      ry: 0.0
      rz: 0.7071068
      rw: -0.7071068
    - id: 'mic2'
      x: -0.45
      y: -0.4
      z: 0.0
      rx: 0.0
      ry: 0.0
      rz: 0.9659258
      rw: 0.258819
    - id: 'mic3'
      x: 0.45
      y: -0.4
      z: 0.0
      rx: 0.0
      ry: 0.0
      rz: 0.258819
      rw: 0.9659258
  # sound_generator:
  sound_sources:
    - file: '500Hz.wav'
      type: 'speaker'
      x: 2
      y: 0
      z: 0
    # - file: '1000Hz.wav'
    #   type: 'speaker'
    #   x: 3.0
    #   y: 6.0
    #   z: 0.0
    # - file: '100652-3-0-0.wav' # dog_bark
    #   type: 'speaker'
    #   x: 6.0
    #   y: 3.0
    #   z: 0.0
    # - file: 'speech019.wav' # speech
    #   type: 'speaker'
    #   x: 6.0
    #   y: 3.0
    #   z: 0.0
    # - file: 'dev_1_ebr_0_nec_5_poly_1.wav' # compilation
    #   type: 'speaker'
    #   x: 6.0
    #   y: 3.0
    #   z: 0.0
    # - file: 'audio_concatenated.wav' # compilation
    #   type: 'speaker'
    #   x: 6.0
    #   y: 3.0
    #   z: 0.0
          